### ISSUE TITLE
How to determine custom firmware has been flashed successfully

### ISSUE THREAD

**Issue by 3guanghui** [Nate711/ODrive#3]
I run 'make' in the 'Firmware' directory and download 'Odrivefirmware.hex' into ODrive by STLink v3. I am not sure if this is the correct operation? How to determine custom firmware has been flashed successfully. Thank you.

**Comment by JacobShenHdu** [comment]
This is the correct operation if there are no problems during compilation. If you download the source code by "git clone", you can check your firmware version through odrivetool(odrv0.version.xxxxx).
