### ISSUE TITLE
the compile environment's problem

### ISSUE THREAD

**Issue by ruixu2** [Nate711/ODrive#5]
with the compiled firmware, it can not work secussfully. 
i can mark the motor work smoothly by python's odrivetool
however, using the aurt protocol, it fails.
i think it maybe the problem of compile's environment or configs.
hoping there is a file describe the config.

**Comment by niranjan1997** [comment]
Hey, @Rare0716 did you got to solve this problem even I have the same issue. Everything works fine when operated through USB and odrive tool but doesn't work In UART protocol. please help me fix this.
